name: release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false # Don't cancel deployments in progress

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: build and deploy
        run: |
          docker compose run --rm \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -e CLOUDFLARE_API_TOKEN=${{ secrets.CF_API_TOKEN }} \
            app \
            bash -c "npx semantic-release && npx wrangler deploy"
